// <auto-generated />
using System;
using CodeFirst.Infrastructure.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Infrastructure.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    partial class CodeFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeFirst.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("ProductId")
                        .HasComment("Identificador del producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Categoria")
                        .HasComment("Categoria del producto");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion")
                        .HasComment("Descripción del producto");

                    b.Property<byte[]>("Images")
                        .HasMaxLength(8000)
                        .HasColumnType("varbinary(8000)")
                        .HasColumnName("Imagen")
                        .HasComment("Imagen del producto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre")
                        .HasComment("Nombre del producto");

                    b.HasKey("Id");

                    b.ToTable("Product", "Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Category No1",
                            Description = "Descripción No1",
                            Name = "Product No1"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Category No2",
                            Description = "Descripción No2",
                            Name = "Product No2"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Category No3",
                            Description = "Descripción No3",
                            Name = "Product No3"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Category No4",
                            Description = "Descripción No4",
                            Name = "Product No4"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Category No5",
                            Description = "Descripción No5",
                            Name = "Product No5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
